---
core:
    num_workers: 20


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Cumulus/hosts.yaml"
        group_file: "/home/ipvzero/Cumulus/groups.yaml"
        defaults_file: "/home/ipvzero/Cumulus/defaults.yaml"
