---
bgp:
  loopback_prefix: "10.10.10.6/32"
  bgp_as: "65002"
  bgp_rid: "10.10.10.6"
  bgp_interfaces:
    swp1:
      bgp_type: external
    swp2:
      bgp_type: external
    swp3:
      bgp_type: external
    swp4:
      bgp_type: external
  advertising: "False"
  bgp_networks: {}
